spring:
  application:
    name: job-service
  datasource:
    url: jdbc:mysql://localhost:3306/job_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    config:
      enabled: false # This is key: it tells the app NOT to look for GitHub configs

jwt:
  secret: "thisIsAtestSecretThatMustBeLongEnoughToWork12345"

cloud:
  aws:
    region: eu-north-1
    s3:
      bucket-name: "arijit-recruiter-saas-2026"
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

eureka:
  client:
    enabled: false